apiVersion: v1
kind: Service

metadata:
  name: springboot-cloud-native-service

spec:
  type: LoadBalancer

  selector:
    app: springboot-cloud-native-service

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080